# Versión del archivo docker-compose
version: "3.3"

services:
  # Servicio de Nginx
  web:
    image: nginx:latest  # Usamos la última imagen de Nginx
    ports:
      - "8080:80"  # Mapeo del puerto 8080 en el host al puerto 80 en el contenedor
    volumes:
      - ./src:/var/www/html  # Mapeo del directorio src al directorio HTML en el contenedor
      - ./default.conf:/etc/nginx/conf.d/default.conf  # Configuración personalizada de Nginx
    links:
      - php-fpm  # Enlazamos el servicio php-fpm

  # Servicio de PHP-FPM
  php-fpm:
    build:
      context: .  # Indica que el Dockerfile está en el mismo directorio que el docker-compose.yml
      dockerfile: Dockerfile  # Nombre del Dockerfile a usar
    volumes:
      - ./src:/var/www/html  # Mapeo del directorio src al directorio HTML en el contenedor
