# Los archivos docker-compose.yml son versionados, lo que significa que es muy importante indicar la versión de las instrucciones que queremos darle.
version: "3.3"

# Servidor nginx
services:
  web:
          # versión
    image: nginx:latest
    # Puerto 8080 
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  # Configuración de php-fpm
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html


  # MariaDB Service
  mariadb:
    container_name: db
    image: mariadb:10.9
    ports:
      - '8306:3306'    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    volumes:
      - './mysqldata:/var/lib/mysql'

  # Adminer
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    restart: always
    ports:
      - "7777:8082"

# Volumes (opcional si solo se usa en mariadb)
volumes:
  mysqldata: